#!/bin/bash

declare TRACE
[[ "${TRACE}" == 1 ]] && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail
set -o noclobber

lint() {
  fd . -t executable | xargs shellcheck -o all
}

main() {
  lint
}

main
