#!/bin/bash

declare TRACE
[[ "${TRACE}" == 1 ]] && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail
set -o noclobber

check() {
  fd . -t executable | xargs shfmt -i 2 -d
}

main() {
  check
}

main
