#!/bin/bash

declare TRACE
[[ "${TRACE}" == 1 ]] && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail
set -o noclobber

readme() {
  rm README.md

  cat <<EOF >README.md
# Gnuplotting-Stuff

## Stuff

  - [dstat](https://github.com/rodmoioliveira/Gnuplotting-Stuff/tree/main/dstat)
  - [wrk2](https://github.com/rodmoioliveira/Gnuplotting-Stuff/tree/main/wrk2)

## Gnuplot References

  - http://gnuplot.info/docs_5.5/Overview.html
  - http://www.gnuplotting.org/
  - https://github.com/Koushikphy/CheatSheets/blob/master/cheatsheets/gnuplot_cheatsheet.md
  - https://github.com/iselab-dearborn/gnuplot-scripts

## Dependencies

  - bat
  - bc
  - dstat
  - fd
  - gawk
  - gnuplot
  - mlr
  - numfmt
  - ripgrep
  - sd
  - sed
  - wrk2
EOF

  sd '(make\[1\]:.+\n)' '' README.md
}

trap readme EXIT
