#!/bin/bash

declare TRACE
[[ "${TRACE}" == 1 ]] && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail
set -o noclobber

test_pwrk2() {
  source ~/.bash_profile
  pwrk2 --help
  fd . -e hgrm |
    pwrk2 \
      --color-bg "black" \
      --color-fg "white" \
      --font Arial \
      --font-scale 2 \
      --height 800 \
      --key-from '(\d{1,10})' \
      --key-to '${1} R/s' \
      --kmargin 7 \
      --line-width 2 \
      --output long.png \
      --preview false \
      --title Long \
      --unit ms \
      --verbose false \
      --width 1800

  fd . -e hgrm |
    pwrk2 \
      --color-bg "black" \
      --color-fg "white" \
      -f Arial \
      -s 2 \
      -g 800 \
      --key-from '(\d{1,10})' \
      --key-to '${1} R/s' \
      -k 7 \
      -l 2 \
      -o short.png \
      -p false \
      -t Short \
      -ums \
      -v true \
      -w 1800

  pwrk2 --sla-new client1.sla
  pwrk2 --sla-new client2.sla
  fd . -e hgrm |
    pwrk2 --sla-plot client1.sla --sla-plot client2.sla --preview false -us
  rm client1.sla client2.sla long.png pwrk2.png short.png
}

main() {
  test_pwrk2
}

main
