#!/bin/bash

declare TRACE
[[ "${TRACE}" == 1 ]] && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail
set -o noclobber

test_pwrk2() {
  pwrk2 --help
  fd . -e hgrm |
    pwrk2 \
      --color-bg "black" \
      --color-fg "white" \
      --font Arial \
      --font-scale 2 \
      --height 800 \
      --key-from '(\d{1,10})' \
      --key-to '${1} R/s' \
      --kmargin 7 \
      --line-width 2 \
      --output long.png \
      --preview false \
      --title Long \
      --unit ms \
      --verbose false \
      --width 1800

  fd . -e hgrm |
    pwrk2 \
      --color-bg "black" \
      --color-fg "white" \
      -f Arial \
      -s 2 \
      -g 800 \
      --key-from '(\d{1,10})' \
      --key-to '${1} R/s' \
      -k 7 \
      -l 2 \
      -o short.png \
      -p false \
      -t Short \
      -ums \
      -v true \
      -w 1800

  pwrk2 --sla-new client1.sla
  pwrk2 --sla-new client2.sla
  fd . -e hgrm |
    pwrk2 --sla-plot client1.sla --sla-plot client2.sla --preview false -us
  rm client1.sla client2.sla long.png plot.png short.png
}

test_pdstat() {
  SHUFFLE=5

  pdstat --help
  fd . -t f -e dstat -e dool |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat --output $0.png --verbose true --color-bg black --color-fg white --font Arial --font-scale 1.1 --height 330 --line-width 2 --output long.png --preview false --title Long --verbose false --width 1500 $0'

  fd . -t f -e dstat -e dool |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat -o $0.png -vtrue --color-bg black --color-fg white -f Arial -s 1.1 -g 330 -l 2 -o short.png -p false -t Short -v true -w 1500 $0'

  fd . -t f -e dstat -e dool |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat -o $0.png -vtrue -p false --x-range 1:10 $0'

  fd . -t f -e dstat -e dool |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat -o $0.png -vtrue -p false --x-range 20:90 --x-mod 2 $0'

  fd . -t f -e dstat -e dool |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat -o $0.png -vtrue -p false --x-mod 2 $0'

  fd . -t f -e csv "dstat/data/csv" |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat --output $0.png --verbose true --color-bg black --color-fg white --font Arial --font-scale 1.1 --height 330 --line-width 2 --output long.png --preview false --title Long --verbose false --width 1500 $0'

  fd . -t f -e csv "dstat/data/csv" |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat -o $0.png -vtrue --color-bg black --color-fg white -f Arial -s 1.1 -g 330 -l 2 -o short.png -p false -t Short -v true -w 1500 $0'

  fd . -t f -e csv "dstat/data/csv" |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat -o $0.png -vtrue -p false --x-range 1:10 $0'

  fd . -t f -e csv "dstat/data/csv" |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat -o $0.png -vtrue -p false --x-range 20:90 --x-mod 2 $0'

  fd . -t f -e csv "dstat/data/csv" |
    shuf -n"${SHUFFLE}" |
    xargs -n1 bash -c 'echo $0; pdstat -o $0.png -vtrue -p false --x-mod 2 $0'
}

main() {
  if [[ "${CI}" == "true" ]]; then
    source ~/.bash_profile
  fi

  test_pwrk2
  test_pdstat
}

main
