#!/bin/bash

#########################################################################
##
## TITLE:         pwrk2
## AUTHOR:        Rodolfo Mói de Oliveira
## DESCRIPTION:   Gnuplot script for plotting latency graphs from
##                wrk2 `--latency` data
## DATE:          07. Mar. 2023
## LICENSE:       MIT
##
#########################################################################

declare TRACE
[[ "${TRACE}" == 1 ]] && set -o xtrace
set -o errexit
set -o pipefail
set -o noclobber

TITLE="Latency Distribution"
FONT="Merriweather"
FONT_SCALE=1
HEIGHT=700
WIDTH=1700
HAS_KEYS=false
KEY_MARGIN=6
LINE_WIDTH=1.5
OPEN_PLOT=true
COLOR_FG="#222222"
COLOR_BG="#f9f9f9"

clean_tempdir() {
  rm -rf "${TMP_DIR}"
}

trap clean_tempdir EXIT

mktempdir() {
  if ! TMP_DIR=$(mktemp -d -t gnuplot-wrk-XXXXXXXXXX); then
    printf 1>&2 "Couldn't create %s\n" "${TMP_DIR}"
    exit 1
  fi

  TMP_DIR_CSV="${TMP_DIR}/csv"
  if ! mkdir "${TMP_DIR_CSV}"; then
    printf 1>&2 "Couldn't create %s\n" "${TMP_DIR_CSV}"
    exit 1
  fi

  TMP_XLABELS_CSV="${TMP_DIR}/xlabels.csv"
  echo "1.0,0.0,0" >"${TMP_XLABELS_CSV}"
  echo "10.0,0.0,90%" >>"${TMP_XLABELS_CSV}"
  echo "100.0,0.0,99%" >>"${TMP_XLABELS_CSV}"
  echo "1000.0,0.0,99.9%" >>"${TMP_XLABELS_CSV}"
  echo "10000.0,0.0,99.99%" >>"${TMP_XLABELS_CSV}"
  echo "100000.0,0.0,99.999%" >>"${TMP_XLABELS_CSV}"
  echo "1000000.0,0.0,99.9999%" >>"${TMP_XLABELS_CSV}"
  echo "10000000.0,0.0,100%" >>"${TMP_XLABELS_CSV}"
}

wrk_to_csv() {
  for file in ${FILES[*]}; do
    filename=$(echo "${file}" | awk -F'/' '{print $NF}' | awk -F'.' '{print $1}')
    csv="${TMP_DIR_CSV}/${filename}.csv"
    sd_cmd="sd '${KEY_FROM}' '${KEY_TO}'"
    data_name=$(echo "${filename}" | eval "$sd_cmd")

    if [[ "${HAS_KEYS}" == true ]]; then
      rg '^ {2,10}\d' --no-filename --no-line-number "${file}" |
        rg request -v |
        rg threads -v |
        awk '{print $4","$1}' |
        sed '1i percentile,'"${data_name}"'' >"${csv}"
    else
      rg '^ {2,10}\d' --no-filename --no-line-number "${file}" |
        rg request -v |
        rg threads -v |
        awk '{print $4","$1}' |
        sed '1i percentile,'"${filename}"'' >"${csv}"
    fi
  done
}

usage_short() {
  local help_text
  help_text=$(
    cat <<"EOF"
Gnuplot script for plotting latency graphs from wrk2 `--latency` data

Usage: pwrk2 [OPTIONS] <FILE>...

Arguments:
  <FILE>...    A list of space-separated FILES in wrk2 `--latency` format

Options:
      --title <TITLE>             Plot title [default: Latency Distribution]
      --color-fg <COLOR>          Set foreground color [default: #222222]
      --color-bg <COLOR>          Set background color [default: #f9f9f9]
      --font <FONT>               Plot font [default: Merriweather]
      --font-scale <FONT-SCALE>   Plot font scale [default: 1]
      --height <HEIGHT>           Plot height [default: 700]
      --width <WIDTH>             Plot width [default: 1700]
      --line-width <LINE-WIDTH>   Plot latency line width [default: 1.5]
      --key-from <REGEX>          Regex to find in the name of <FILE>, used to set key labels
      --key-to <REPLACE>          Regex to replace the name of <FILE>, used to set key labels
      --key-margin <MARGIN>       Bottom plot margin for key labels [default: 6]
      --open <BOOL>               Whether or not should open the plot after generation [default: true] [possible values: true, false]
  -o, --output <OUTPUT>           Output plot file [default: pwrk2.png]
  -h, --help                      Print help information (use `--help` for more detail)
EOF
  )

  printf 1>&2 "%s\n" "${help_text}"
}

usage_long() {
  local help_text
  help_text=$(
    cat <<"EOF"
Gnuplot script for plotting latency graphs from wrk2 `--latency` data

Usage:
  pwrk2 [OPTIONS] <FILE>...

Arguments:
  <FILE>...
          A list of space-separated FILES in wrk2 `--latency` format

Options:
      --title <TITLE>
          Plot title [default: Latency Distribution]

      --color-fg <COLOR>
          Set foreground color [default: #222222]

      --color-bg <COLOR>
          Set background color [default: #f9f9f9]

      --font <FONT>
          Plot font [default: Merriweather]

      --font-scale <FONT-SCALE>
          Plot font scale [default: 1]

      --height <HEIGHT>
          Plot height [default: 700]

      --width <WIDTH>
          Plot width [default: 1700]

      --line-width <LINE-WIDTH>
          Plot latency line width [default: 1.5]

      --key-from <REGEX>
          Regex to find in the name of <FILE>, used to set key labels

      --key-to <REPLACE>
          Regex to replace the name of <FILE>, used to set key labels

      --key-margin <MARGIN>
          Bottom plot margin for key labels [default: 6]

      --open <BOOL>
          Whether or not should open the plot after generation [default: true] [possible values: true, false]

  -o, --output <OUTPUT>
          Output plot file [default: pwrk2.png]

  -h, --help
          Print help information (use `-h` for a summary)

Get some data:
  wrk2 -t1 -c1 -d30s -R1 --latency "http://jsonplaceholder.typicode.com/todos/1" | tee 1.wrk
  wrk2 -t8 -c10 -d30s -R10 --latency "http://jsonplaceholder.typicode.com/todos/1" | tee 10.wrk
  wrk2 -t8 -c25 -d30s -R25 --latency "http://jsonplaceholder.typicode.com/todos/1" | tee 25.wrk

Plot from data:
  fd . -e wrk | pwrk2
  pwrk2 *.wrk

Rename plot labels:
  fd . -e wrk | pwrk2 --key-from '(\d{1,10})' --key-to '${1} R/s' --output data/plot/pwrk2.png

Change plot styles:
  fd . -e wrk | pwrk2 \
    --color-bg "#000000" \
    --color-fg "#ffffff" \
    --font 'Roboto' \
    --font-scale 1.5 \
    --line-width 3 \
    --width 1500 \
    --height 1200 \
    --key-margin 7
EOF
  )

  printf 1>&2 "%s\n" "${help_text}"
}

error_no_input() {
  printf 1>&2 "No <FILES> input ...\n"
  printf 1>&2 "\nFor more information try '--help'\n"
  exit 1
}

error_keys() {
  printf 1>&2 "if some --key-{from,to} is present, the other must also be present ...\n"
  printf 1>&2 "\nFor more information try '--help'\n"
  exit 1
}

error_open() {
  printf 1>&2 "the flag --open <BOOL> must be 'true' or 'false' ...\n"
  printf 1>&2 "\nFor more information try '--help'\n"
  exit 1
}

deps_validate() {
  summary=()
  is_valid=true

  deps=("bc" "gawk" "getopt" "gnuplot" "rg" "sd" "sed")
  for dep in "${deps[@]}"; do
    if ! command -v "${dep}" &> /dev/null; then
      summary+=("[Missing] ${dep}")
      is_valid=false
    else
      summary+=("[OK] ${dep}")
    fi
  done

  if [[ "${is_valid}" == false ]]; then
    2>&1 printf "You have missing dependencies.\n"
    2>&1 printf "You must install the missing dependencies for pwrk2 work correctly.\n\n"
    2>&1 printf "%s\n" "${summary[@]}"
    exit 1
  fi
}

args_parse() {
  local args
  if ! args=$(getopt -a -n pwrk2 -o ho: --long help,open:,output:,width:,height:,font:,title:,font-scale:,line-width:,key-from:,key-to:,key-margin:,color-fg:,color-bg: -- "$@"); then
    printf 1>&2 "\nFor more information try '--help'\n"
    exit 1
  fi
  eval set -- "${args}"

  while [[ $# -gt 0 ]]; do
    case "$1" in
    -o | --output)
      shift
      OUTPUT="$1"
      ;;
    --width)
      shift
      WIDTH="$1"
      ;;
    --height)
      shift
      HEIGHT="$1"
      ;;
    --font)
      shift
      FONT="$1"
      ;;
    --font-scale)
      shift
      FONT_SCALE="$1"
      ;;
    --line-width)
      shift
      LINE_WIDTH="$1"
      ;;
    --title)
      shift
      TITLE="$1"
      ;;
    --key-from)
      shift
      KEY_FROM="$1"
      ;;
    --key-to)
      shift
      KEY_TO="$1"
      ;;
    --key-margin)
      shift
      KEY_MARGIN="$1"
      ;;
    --color-fg)
      shift
      COLOR_FG="$1"
      ;;
    --color-bg)
      shift
      COLOR_BG="$1"
      ;;
    --open)
      shift
      OPEN_PLOT="$1"
      ;;
    -h)
      usage_short
      exit 0
      ;;
    --help)
      usage_long
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *) usage_long ;;
    esac
    shift
  done

  if [[ -p /dev/stdin ]]; then
    FILES="$(cat -)"

    if [[ -z "${FILES}" ]]; then
      error_no_input
    fi
  else
    FILES=()
    while IFS= read -r i; do FILES+=("${i}"); done < <(echo "$@")

    if [[ -z "${FILES[*]}" ]]; then
      error_no_input
    fi
  fi
}

arg_key() {
  if [[ -z "${KEY_FROM}" && -z "${KEY_TO}" ]]; then
    HAS_KEYS=false
  elif [[ -z "${KEY_FROM}" && -n "${KEY_TO}" ]]; then
    error_keys
  elif [[ -n "${KEY_FROM}" && -z "${KEY_TO}" ]]; then
    error_keys
  else
    HAS_KEYS=true
  fi
}

arg_open() {
  if ! [[ "${OPEN_PLOT}" == true || "${OPEN_PLOT}" == false ]]; then
    error_open
  fi
}

arg_output() {
  if [[ -z "${OUTPUT}" ]]; then
    OUTPUT_FILE="pwrk2.png"
  else
    OUTPUT_FILE="${OUTPUT}"
  fi
}

args_validate() {
  arg_key
  arg_open
  arg_output
}

calc_font_size() {
  echo "${1} * ${FONT_SCALE}" | bc
}

plot_draw() {
  local counter=1
  local -a csv_files
  local plot_directives="plot '${TMP_XLABELS_CSV}' with labels center offset 0, -1 tc \"${COLOR_FG}\" notitle, '${TMP_XLABELS_CSV}' with points pt 1 lc \"${COLOR_FG}\" ps 2 notitle, "

  while IFS= read -r q; do csv_files+=("${q}"); done < <(ls -1v "${TMP_DIR_CSV}")
  for csv in "${csv_files[@]}"; do
    plot_directives+=$(printf '"%s" using 1:2 with lines linestyle %d, ' "${TMP_DIR_CSV}/${csv}" "${counter}")
    counter=$((counter + 1))
  done

  gnuplot <<EOF
set terminal pngcairo enhanced background rgb "${COLOR_BG}" size "${WIDTH}","${HEIGHT}" font "${FONT},$(calc_font_size 16)"

set border linecolor rgb "${COLOR_FG}"
set grid linecolor rgb "${COLOR_FG}"
set key textcolor rgb "${COLOR_FG}"
set title textcolor rgb "${COLOR_FG}"
set xlabel textcolor rgb "${COLOR_FG}"
set xtics textcolor rgb "${COLOR_FG}"
set ylabel textcolor rgb "${COLOR_FG}"
set ytics textcolor rgb "${COLOR_FG}"

set title "${TITLE}" font "${FONT}-Bold,$(calc_font_size 24)"
set datafile separator ','

set tics out font ",$(calc_font_size 12)"
set xtics rotate
set grid back xtics ytics

set key bottom center outside autotitle columnhead font ",$(calc_font_size 14)" horizontal
set ylabel "Milliseconds" offset 0,0 font "${FONT}-Bold,$(calc_font_size 14)"
set xlabel "Percentile" offset 0,-1.5 font "${FONT}-Bold,$(calc_font_size 14)"

set style line  1 linecolor rgb '#a6cee3' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line  2 linecolor rgb '#1f78b4' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line  3 linecolor rgb '#b2df8a' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line  4 linecolor rgb '#33a02c' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line  5 linecolor rgb '#fb9a99' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line  6 linecolor rgb '#e31a1c' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line  7 linecolor rgb '#fdbf6f' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line  8 linecolor rgb '#ff7f00' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line  9 linecolor rgb '#cab2d6' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line 10 linecolor rgb '#6a3d9a' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line 11 linecolor rgb '#ffff99' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1
set style line 12 linecolor rgb '#b15928' linetype 1 linewidth ${LINE_WIDTH} pointtype 1 pointsize 1

set logscale x
unset xtics
set bmargin "${KEY_MARGIN}"

set border back
set output "${OUTPUT_FILE}"

set terminal pngcairo font ",$(calc_font_size 12)"
$(echo "${plot_directives}" | sd ", $" '')
exit
EOF
}

plot_open() {
  if [[ "${OPEN_PLOT}" == true ]]; then
    unameOut="$(uname -s)"

    case "${unameOut}" in
      Linux*) xdg-open "${OUTPUT_FILE}" ;;
      Darwin*) open "${OUTPUT_FILE}" ;;
      CYGWIN* | MINGW* | *) ;;
    esac
  fi
}

main() {
  deps_validate
  args_parse "$@"
  args_validate
  mktempdir
  wrk_to_csv
  plot_draw
  plot_open
}

main "$@"
