#!/bin/bash

declare TRACE
[[ "${TRACE}" == 1 ]] && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail
set -o noclobber

readme() {
  cat <<EOF >|./dstat/README.md
# pdstat

pdstat is a Gnuplot script for plotting graphs from [dstat](https://github.com/dstat-real/dstat) and [dool](https://github.com/scottchiefbaker/dool) metric data.

## Dependencies

  - [bc](https://linux.die.net/man/1/bc)
  - [gawk](https://www.gnu.org/software/gawk/)
  - [getopt](https://man7.org/linux/man-pages/man3/getopt.3.html)
  - [gnuplot](http://www.gnuplot.info/)
  - [numfmt](https://man7.org/linux/man-pages/man1/numfmt.1.html)
  - [rg](https://github.com/BurntSushi/ripgrep)
  - [sd](https://github.com/chmln/sd)

## Roadmap

- [x] Add units for each metric
- [ ] Add flags filters to exclude and include the metrics to plot
- [x] Add flags to slice data intervals
- [x] Add flags to step data intervals
- [ ] Add flags to change metrics unit Gi, Mi, Ki, Gb, Mb, Kb; (?)

## Usage

\`\`\`txt
$(./dstat/pdstat 2>&1 --help)
\`\`\`

## Result

<p align="center">
  <img src="https://raw.githubusercontent.com/rodmoioliveira/Gnuplotting-Stuff/main/$(fd "all.png" dstat/plot/csv/dstat/default) ">
</p>

EOF

  sd '(make\[1\]:.+\n)' '' README.md
}

trap readme EXIT
