#!/bin/bash

declare TRACE
[[ "${TRACE}" == 1 ]] && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail
set -o noclobber

readme() {
  cat <<EOF >|./wrk2/README.md
# pwrk2

pwrk2 is a Gnuplot script for plotting latency graphs from [wrk2](https://github.com/giltene/wrk2) \`--latency\` data.
It takes its inspiration from the [original](https://github.com/HdrHistogram/HdrHistogram/blob/master/gnuplotExample/make_percentile_plot)
Gnuplot script written by [Gil Tene](https://github.com/giltene).

## Dependencies

  - [bc](https://linux.die.net/man/1/bc)
  - [gawk](https://www.gnu.org/software/gawk/)
  - [getopt](https://man7.org/linux/man-pages/man3/getopt.3.html)
  - [gnuplot](http://www.gnuplot.info/)
  - [rg](https://github.com/BurntSushi/ripgrep)
  - [sd](https://github.com/chmln/sd)

## Usage

\`\`\`txt
$(./wrk2/pwrk2 2>&1 --help)
\`\`\`

## Result

<p align="center">
  <img src="https://raw.githubusercontent.com/rodmoioliveira/Gnuplotting-Stuff/main/wrk2/data/plot/pwrk2.png">
</p>

EOF

  sd '(make\[1\]:.+\n)' '' README.md
}

trap readme EXIT
