name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TRACE: 0

jobs:
  tests:
    name: '[Gnuplotting-Stuff] Test on ${{ matrix.os }}'

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - { os: ubuntu-latest }
          - { os: macos-latest }

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies ${{ matrix.os }}
      run: make dependencies

    - name:  Check format bash code ${{ matrix.os }}
      run: make code-fmt-check

    - name:  Check lint bash code ${{ matrix.os }}
      run: make code-lint

    - name: Check typos ${{ matrix.os }}
      run: make typos

    - name: Symlink scripts ${{ matrix.os }}
      run: make symlink

    - name: Test pwrk2 ${{ matrix.os }}
      run: source ~/.bash_profile; pwrk2 --help; fd . -e wrk | pwrk2 --color-bg "black" --color-fg "white" --font Arial --height 800 --line 2 --kmargin 7 --output long.png --preview false --scale 2 --title Long --verbose false --width 1800 --key-from '(\d{1,10})' --key-to '${1} R/s'; fd . -e wrk | pwrk2 --color-bg "black" --color-fg "white" -f Arial -g 800 -l 2 -k 7 -o short.png -p false -s 2 -t Short -v true -w 1800 --key-from '(\d{1,10})' --key-to '${1} R/s'

    - name: Unsymlink scripts ${{ matrix.os }}
      run: make unsymlink
