name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TRACE: 1

jobs:
  tests:
    name: '[Gnuplotting-Stuff] Test on ${{ matrix.os }}'

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - { os: ubuntu-latest }
          - { os: macos-latest }

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies ${{ matrix.os }}
      run: make dependencies

    - name:  Check format bash code ${{ matrix.os }}
      run: make code-fmt-check

    - name:  Check lint bash code ${{ matrix.os }}
      run: make code-lint

    - name: Check typos ${{ matrix.os }}
      run: make typos

    - name: Symlink scripts ${{ matrix.os }}
      run: make symlink

    - name: Test pwrk2 ${{ matrix.os }}
      run: pwrk2 --help

    - name: Unsymlink scripts ${{ matrix.os }}
      run: make unsymlink
